version: '3'
services:
  postgres:
    build:
      context: .
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'pg'
      PGDATA: /var/lib/postgresql/data/pgdata
    container_name: postgres-db
    volumes:
      - ./work:/work
      - ./db/postgres:/var/lib/postgresql/data
      - ./db/logs:/var/log
